### ISSUE TITLE
HTTPS Connection never connects when using VPN

### ISSUE THREAD

**Issue by ivan-elude** [deric/es-dedupe#13]
Hey @deric , thanks for an awesome project! I pulled down the latest docker image, but the tool seems to be getting stuck on the initial connection. I've enabled all possible logs, but not seeing useful insights. Do you have any tips?

```
docker run --rm deric/es-dedupe:latest esdedupe -H https://my.ssl.host.here -P 443 --prefix filebeat -f time --ssl -l DEBUG --es-level DEBUG
```

The output that I see is:
```
2022-07-18T21:49:54  [140150432298816] INFO  esdedupe Starting esdedupe: 2.0.0 - duplicate document removal tool
2022-07-18T21:49:54  [140150432298816] DEBUG esdedupe GET https://my.ssl.host.here:443
2022-07-18T21:49:54  [140150432298816] DEBUG urllib3.connectionpool Starting new HTTPS connection (1): my.ssl.host.here:443
```

I've checked with `curl`, and I can hit `https://my.ssl.host.here:443` and get back the elastic search details:

```
{
  "name" : "REDACTED",
  "cluster_name" : 'REDACTED",
  "cluster_uuid" : "REDACTED",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2022-02-10T09:41:23.620550Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

I'm running ElasticSearch on AWS.

Thank you in advance for any tips.

**Comment by deric** [comment]
That's weird, [it uses](https://github.com/deric/es-dedupe/blob/master/esdedupe/esdedupe.py#L56) pretty much standard Python [requests](https://pypi.org/project/requests/) library. It should be the same as running 

```
curl -XGET https://my.ssl.host.here:443
```

**Comment by ivan-elude** [comment]
Interesting. I was able to dig a little deeper and I figured out that this is due to the resource I'm hitting being on a corporate VPN (Tailscale). I was able to run curl in an alpine image and it can't reach the address, while the local curl can. 

I was able to get the curl command working with:

```
docker run -it --network host alpine

# apk add curl
# curl -XGET https://my.ssl.host.here:443
```

I was then able to patch my `es-dedupe` command as follows:

```
docker run --rm --network host deric/es-dedupe:latest esdedupe -H https://my.ssl.host.here -P 443 --prefix filebeat -f time --ssl -l DEBUG --es-level DEBUG
```

I then encountered the same issue as #12, so I will try that fix next.

Posting here so that folks are aware that using a VPN with this docker image may not work as expected - hope it's useful to future treasure hunters!

https://xkcd.com/979/

**Comment by ivan-elude** [comment]
Closing issue, as adding `--network host` and building locally as per #12 was enough to run my jobs.
