### ISSUE TITLE
Index matching fails - no dupes removed

### ISSUE THREAD

**Issue by tblake84** [deric/es-dedupe#5]
Running the script with the following:
```
python3 -u dedupe.py -H localhost -P 9200 -i twitter -f id > es_dedupe.log
```

It runs fine but fails to find the index properly:
```
2018-03-29 13:51:07.077141 dedupe.py::main: == Starting ES dupe deleter....
2018-03-29 13:51:07.140865 dedupe.py::main::run: The following indices matched your name pattern http://localhost:9200/twitter/_stats :
{   }

2018-03-29 13:51:07.141239 dedupe.py::main::run: == successfully completed dupe deletion. Took: 0:00:00.063711
```

For example, I have the following records in my ES database both with the same value in the 'id' field:
```
{
  "_index": "twitter",
  "_type": "tweet",
  "_id": "51462955",
  "_version": 905,
  "_score": null,
  "_source": {
    "channel_value": "",
    "master_id": "XXXXXXXXXXXXXXXXX",
    "esn": "afgehs",
    "or": "O",
    "base_station": "node01",
    "id": "51462955"
  }
}
```

I would expect one of these records to be removed but they are both present still.
Not sure what I am doing wrong here but it looks like the index designation isn't correctly finding an index that exists in my DB.

I am using ES 6.2.1.

**Comment by fkrueger** [comment]
I added a pull request to this repository, that should fix the issue (and then some), in case you are interested: https://github.com/deric/es-deduplicator/pull/6

**Comment by deric** [comment]
@tblake84 Please try updated version from master. Feel free to reopen the issue if the problem persists.
