### ISSUE TITLE
illegal_argument_exception: Rejecting mapping update to [blockchain] as the final mapping would have more than 1 type: [_doc, nginx.access]

### ISSUE THREAD

**Issue by theirman** [deric/es-dedupe#8]
Hello
I tried to deduplicate 24 hours of duplicates data in ES with your script using the following command : ** python3 -u dedupe.py -H 10.10.10.21 -P 9200 -i blockchain -f hash.keyword**

i've this problem : 
![es-dedup](https://user-images.githubusercontent.com/15727858/74158138-d2a2cf00-4c19-11ea-92b6-f82fd280a97f.PNG)

What do i wrong ?

**Comment by deric** [comment]
Which Elastic version do you use? Is it 6 or newer? See [types removal post](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html).

**Comment by theirman** [comment]
I'm new using ElasticSearch and Kibana
I use ES and Kibana version 7.5

**Comment by theirman** [comment]
For those who would encounter this problem, i resolve this problem this way :

- I create a pipeline **set-id** to rewrite **hash** of the record in my **_id**
- I reindex my index **blockchain** in a new index called **blockchain2** using the pipeline **set-id**
- I delete my index **blockchain** and recreate it using the same mapping.json
- I reindex my index **blockchain2** in my new index **blockchain**

And it works, I have all my records in my new index **blockchain** without the duplicates

**Comment by deric** [comment]
The problem is that the default type was set to `nginx.access` which was ok for my use case, but not really universal value. You could use the `-t _doc` argument to change it.
