### ISSUE TITLE
README.md: dedupe should be renamed to esdedupe

### ISSUE THREAD

**Issue by ilyaevseev** [deric/es-dedupe#9]
It seems that dedupe was renamed to esdedupe but README.md still contains old name.

**Comment by deric** [comment]
Yes, sorry about that. The documentation is far behind the code. I'll try to update it to reflect all the changes. In fact the old script is still present in the repository, so it should work. The "new" version is structured as a python package and uses features from newer Elasticsearch versions. I just didn't have time to merge it without making too many breaking changes.

**Comment by deric** [comment]
Updated documentation to match the correct name.
